apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pterodactyl-ingress
  namespace: pterodactyl
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`panel.gameserver.rafa.run`)
      kind: Rule
      middlewares:
#        - name: default-headers
#          namespace: default
      services:
        - name: pterodactyl
          port: 80
  tls:
    secretName: gameserver-rafa-run-tls